pipeline {
    agent any

    environment {
        gv = load 'jenkins/script.groovy'
    }

    parameters {
        choice(name: "VERSION", choices: ['1.1', '1.2', '1.3'], description: 'version')
        booleanParam(name: "executeTests", defaultValue: true, description: 'approve tests')
    }

    stages {

        stage ("build") {

            steps {
                script {
                    gv.buildApp()
                }

            }
        }

        stage ("test") {

            steps {
                when {
                    expression {
                        params.executeTests
                    }
                }

                script {
                    gv.testApp()
                }

            }
        }

        stage ("deploy") {

            steps {
                script {
                    gv.deployApp()
                }

            }
        }
    }

}