@Library('jenkins-shared-library')
def gv

pipeline {
    agent any
    environment {
        REPOSITORY='jokerwrld/java-maven-app:2.0'
    }
    stages {

        stage ("init") {
            steps {
                script {
                    gv = load 'stages.groovy'
                }
            }
        }
        stage ("build jar") {
            steps {
                script {
                    buildJar()
                }
            }
        }
        stage ("build image") {
            steps {
                script {
                    buildImage()
                }
            }
        }
        stage ("deploy app") {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
    }
}
